### ISSUE TITLE
Enable passing executable name/path for mrbayes(), and maybe others.

### ISSUE THREAD

**Issue by ddiez** [heibl/ips#1]
As per [this question](https://www.biostars.org/p/235664/) asked in Biostars, it would be nice to be able to pass the path to the executable in functions like `mrbayes()`, so that it can adapt to the installation idiosyncrasies. In particular, currently it seems problematic in Windows (which I haven't tested, but the OP on that Biostars question has).

**Comment by heibl** [comment]
Yes, you are right! I have just pushed a new version of _ips_ that allows for giving an explicit path via an argument `exec` in `mrbayes`. Thanks for pointing this out!
